### PR TITLE
another doubling in performance

### PR DESCRIPTION
**Pull request by berndhopp**
@berndhopp
some more optimizations: 
 - the avoidance of substring(), which eliminates the need to allocate new char-arrays
 - hexDigit() now uses a simple switch-case, which is (probably) a tiny bit faster than the former implementation
 - avoid bitshifting by parsing complete long at once
 - byte is sufficient for parsed hex

test results now show performance at 7.96 times better than UUID::fromString. I don't see any more optimizations possible at this point.

Benchmark                            Mode  Cnt      Score     Error   Units
FastUuidParserBenchmark.fromString  thrpt   20  16921.608 ± 258.043  ops/ms
NormalUUIDBenchmark.fromString      thrpt   20   2124.604 ±  13.355  ops/ms

### CODE REVIEW

**Comment by komamitsu** [comment]
@berndhopp Thanks for the contribution.

I benchmarked with this pull request using OpenJDK 1.8.0_181 on macOS (High Sierra and Linux 4.4.0). But I couldn't see any significant performance improvement comparing to the original version.

What platform and Java version did you use for the benchmark?

**Comment by berndhopp** [comment]
Hello @komamitstu, 

I was running it on a macbook pro 2015 with high sierra 10.13.6 and jdk 1.8.0_60. It's reproducible on my system.

Benchmark                            Mode  Cnt      Score     Error   Units
FastUuidParserBenchmark.fromString  thrpt   20  15944.113 ± 858.000  ops/ms
NormalUUIDBenchmark.fromString      thrpt   20   2199.681 ±  39.498  ops/ms

**Comment by berndhopp** [comment]
@komamitsu could you try again, please? The avoidance of substring Operations itself must give a substantial Performance boost, so I think my stats are correct.

**Comment by komamitsu** [comment]
@berndhopp I just made `.travis.yml` run JMH on TravisCI (https://github.com/komamitsu/fast-uuid-parser/pull/4)
Could you rebase your pull request to the latest master?

**Comment by komamitsu** [comment]
I confirmed this pull request improves the performance by about 18% according to the benchmark results on TravisCI.

Great work!
Thanks @berndhopp

**Pull request merged**
